AppBundle\Entity\Deportista:
    type: entity
    table: deportista
    id:
        iddeportista:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: IdDeportista
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Nombre
        nacionalidad:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: Nacionalidad
        edad:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: Edad
        telefono:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: Telefono
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Email
    lifecycleCallbacks: {  }
